### ISSUE TITLE
Adding support for more slots

### ISSUE THREAD

**Issue by authorless** [vasanex/ItemQuickSwitchMod#2]
Add support for this mod [HotbarPlus](https://thunderstore.io/c/lethal-company/p/FlipMods/HotbarPlus/) that adds more slots. I wanted to add 6 slots for the game through the config, but in the end the mod reset them to 4.

**Comment by vasanex** [comment]
You don't need ItemQuickSwitch if you already have HotbarPlus since the latter also adds support for Keybinds as far as I know. You can just remove IQS and use the keybindings provided by HotbarPlus.
