### ISSUE TITLE
v45 Update

### ISSUE THREAD

**Issue by heyot6** [vasanex/ItemQuickSwitchMod#3]
Changes from v45 update of vanilla game. 
Not sure if this is related to the game creator adding the ability to set keybinds in the latest patch.

Item quickswitch no longer working when pressing slots 1, 2, 3, and 4.

The ability to set keybinds for the individual item slots is still missing from the vanilla game

**Comment by vasanex** [comment]
Hi, do you have any other mods installed that might interfere with ItemQuickSwitch?

From my (very limited) testing it seems like IQS should still work fine even after the update. I also got reports on the modding discord that the plugin still works.

I will have a look at the updated game code though and maybe push an update if it is needed.

**Comment by heyot6** [comment]
So sorry about the false flag. I realized that I had accidentally swapped profiles on my Logitech mouse. Thanks again for the great mod, it's a huge QoL improvement!
